version: '3.8'

x-common-variables: &common-variables
    MYSQL_USER: 'bbs'
    MYSQL_PASSWORD: '***CHANGE_HERE***'

services:
    db:
        image: mysql:5.7
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/initdb.d:/docker-entrypoint-initdb.d
        environment:
            <<: *common-variables
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_USER: bbs
            TZ: "Asia/Tokyo"

    nginx:
        build: ./nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/ssl:/etc/nginx/ssl
            - ./www:/var/www/html
            - ./data:/var/www/boar-img-data
        depends_on:
            - php

    php:
        build: ./php
        volumes:
            - ./www:/var/www/html
            - ./data:/var/www/boar-img-data
        depends_on:
            - db
        environment:
            <<: *common-variables

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8080:80
        depends_on:
            - db