version: '3.8'

x-common-variables: &common-variables
  MYSQL_HOST: 'db'
  MYSQL_USER: 'bbs'
  MYSQL_PASSWORD: 'bbs_dev'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - apache_db
    environment:
      <<: *common-variables
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      TZ: "Asia/Tokyo"

  apache:
    build: ./apache
    volumes:
      - ./www:/var/www/html
      - ./data:/var/www/data
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    depends_on:
      - db
    networks:
      - apache_db
      - apache_internet
    environment:
      <<: *common-variables
      ADMIN_REGISTER_SECRET: 'xxxxxxxxxxx'
      JWT_PRIVATE_KEY: 'LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdnN0TWhQdm5UaTZYSjdiYWFxODl1WEVJUlFkK09Yc1ZoeWlYOFNReTlqYlFVcWlxCldwbzcxNXUxWHdENG5Kci9hbjlzVWRCSHAwRVN5RDl5VW9CdGNJcUU0Q21wVFZoQVh6QWp1V1hYMnFpTVdFNEoKSDFHSmpwRzBSdFkyVGZJekZVRHVxcmJqUUgxaGVodFE5OTVUaGp2aUpQZStPSEhBTmtvSC9PaEk1UFdiWTlXRApBK3IxdnpHZlorbzRkQXBRYStSOGtheGQ5ek9FRWlha1dWeFNOWVc5QXF1Uk5NRXM5NzlZTjBwR0haYk9xSXZtCnM4dDkrem9HT2FrZWhlTjY2WGE5Ly9sRDNVNnRJcUxZejdqSDd1WHFKQnhDN0xXK3FlVDZESG9adXJQeisxdlEKM2xvMHRHdS92SFhsMEJyVFgzUDZNRzV2aVVNSEh1QWNnUlRtelFJREFRQUJBb0lCQUJxYjE4d2tKWm90dlQ3NApyWFY3Z3l3OXExMlZNZkZxVFJKUWd3QktnQ0QrZkFkTEpwY0VNNXhhUnUwOUFXODEzckZIbkIrODRJRmUvZk9YCmhhWWo2eDlxOGlVaEtrOXpJMmNqRzVoYnI4TDdCcmU2Q21PbngzdHVycW5DYmtob290OHY4eGt6OEhXcUJ0STAKeFJJTW03RjQ0STB2VUFRbk9SdFpMOHdCeVVqRkNneVlGbmtLUy9OdVhYQy94bWFaa3RNM0VXSkhHTm1jdDVOdgpRbVpiRi96TUsxcVFJSklsNkYrdHVDMy9oQVdKa3dDSzFUbkRGaHJhT3k0SnhVZHllamRNUWxJeHVSTEprdFFWCmtFS3Zob1FPeFdxekoxcEdsbjE2cXRVaDlHRXp5L0FHWlVwaTNLUzJyaXZ1WFQxRi9DdWdNdHFiVEFkdmNla3UKYm1SbEZyRUNnWUVBK2lLemZ0OFVEb1pzZXJyR0s5TnFINXo2MGpVQ2tIVDc3dFVtelpRRnFxSnJ0T2I3dmdSYgpYMWpjZUNrR2N3eXBxNUpQbFdCK3cwQXFkdVF0cFB3Q0FTQW5ON3Nob0RhL3oyS1B5QkgrNm9MY3dzNklLekZlCmExOW9BeWhzQ2dLTzB1QzdST0NGU3VQT1JBeER5Q2g1NFd2YmY0akd0UUw5Y0xnTjZXSUhQRU1DZ1lFQXcwUnYKSDFZNXNMbHU5c1JNU3pCQlhuOFhQemdEcmVVWm91YjlOZlNUVDlxd0N0VWVpakRHd1VDYkxVRjVOV2RDdDNsVgp6K2lGaU83UHdVdENzUytXWFoybzRoR2tINmk1Z1p4dnRXejBiUE5XaDA2ZHlFSkorTVBLSmRiUUVFMllSUFhRCmRnTEJ5RlFOR2V1cjNYZ0pHT1VGVHNWSXd0bkFyU0NReUg4eHA2OENnWUVBeWo1V2ZTVm5kUnNSQ09hTkpwQkkKeFFqSzhEMTJObEN3Qm5xSFpqN2htZ2E3S1VoOWtUUzZvRXdiN25mVlJCNmY3UjVlaEh2QjRxSzE4dTBwVHJXSAo5VnNHK3BPdWEzajQrM2hJb3M2U0d4RDE1L2pQdG9TelFBT2krTEt0TUNiRFRoUHd0bzhHbHZlOEpkNzR5eFNXCi8wR1M5dm9qRitZei92aUNId3BvcVRzQ2dZRUFubHQ0ZHdSNWdzM1BwTVpyVFNyVVNLdHZFZkQrWXQrQ1crOVMKZUpoaGc0aEo3bThKOW00Nk1lMlFLektHOXYxSVNQMVl6MlMyTHVmbGlzL2JSVkRmZEFweE5PMnptWTArN0ZNTwo4U1pzVDVORW9EVHNsc1RUc3JBdDEyUVBscmttL1A0UlVqTklMb3VqbUZyZEpaMjhXdmtZeGRvTytSNlpPSTVKCmZLQlNoN2NDZ1lCd0Ezdzg4NjRJT3BZK20yOG1mNEU1RUZwbTlnMlgyNmxrY1ZhYzlLd1lHWFlCUjFnM0RlQkgKa25nMHJpdTF0UWJSTDQwSnZnYk1tMDlJMDQxY1VIbkhaUEE4YjFQdlRpcjFXNlhlUXdxUFYvMktPNEdyTzFSRApSRlVPbjFYU04ya05jSjk2TnI5V3Y2bCtHMHVxQ0ZZSXZsUng5bDJLUUxoc2sxdWlSVG5zc2c9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo='
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - apache_db
      - apache_internet
networks:
  apache_db:
    name: bbs__apache_db
    internal: true
  apache_internet:
    name: bbs__apache_internet